# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task -l
    silent: true

  install-yd-base-tools:
    desc: install cli mininum
    cmds: [task install-all -o prefixed -t vparts/install_yd_base_tools.tasks.yml]

  install-conda-mini:
    desc: install cli mininum
    cmds: [task install-all -o prefixed -t vparts/install_conda_mini.tasks.yml ]

  install-docker:
    desc: install cli mininum
    cmds: [task install-all -o prefixed -t vparts/install_docker_base.tasks.yml ]


  install-all:
    desc: Install all development tools
    deps:
      - task: install-yd-base-tools
      - task: install-conda-mini
      - task: install-docker
    cmds:
      - echo "Successfully Installed ALL"
