# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task -l
    silent: true

  install-all:
    desc: _
    cmds:
      - task: install-all-seq2

  install-all-par:
    desc: Install all development tools
    silent: true
    env:
      to_docker: '{{.to_docker}}'
    deps:
      - task: install_part2 
        vars: {part_path: vparts/install_yd_base_tools.tasks.yml}
      - task: install_part2 
        vars: {part_path: vparts/install_conda_mini.tasks.yml }
      - task: install_part2 
        vars: {part_path: vparts/install_docker_base.tasks.yml }
      - task: install_part2 
        vars: {part_path: vparts/install_yd_base_zsh.tasks.yml }
    cmds:
      - echo "Successfully Installed ALL"

  install-all-seq2:
    desc: Install all development tools
    vars:
      silent_opt: '{{if .to_docker}}--silent{{end}}'
    env:
      to_docker: '{{.to_docker}}'
    cmds:
      - task {{.silent_opt}} install_part2 part_path=vparts/install_yd_base_tools.tasks.yml
      - task {{.silent_opt}} install_part2 part_path=vparts/install_conda_mini.tasks.yml
      - task {{.silent_opt}} install_part2 part_path=vparts/install_docker_base.tasks.yml
      - task {{.silent_opt}} install_part2 part_path=vparts/install_yd_base_zsh.tasks.yml

  install_part2:
    desc: '{{.TASK}} install logical part block from file.'
    vars:
      __args: |-
          part_path: "path to installer"
      _docker_repr: |-
        COPY {{.part_path}} /src/{{.part_path}}
        RUN  task install-all -o prefixed -t /src/{{.part_path}}
      _tasker_repr: task install-all -o prefixed -t {{.part_path}}
    cmds: 
    - |-
      if [[ "$to_docker" != "" ]]; then
      echo '
      {{._docker_repr}}
      '
      else
        {{._tasker_repr}}
      fi

  to_dockerfile:
    desc: _
    cmds:
     - to_docker=1 task install-all-seq2 2>/dev/null

  test:
    desc: _
    cmds:
      - task run-test -d tests/ubuntu-20.4-yd
